# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28521098f0f486c8f8afa81cf43b0b8ea99c062b70e538bc5bb5a82a3a55157af332904a5b3246765f7cf33e8ef515c12c910b91179283e0199dd04b56121cb4

test:
  secret_key_base: 72783f03667cdcfd77c404b4c556e844bcec4d1fcebcd471fd0df972a9d8579e298f00fe469da8ed8ff10f5027b50a13023bbfb44a46b24f94ca05f049c5ffd7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
